name: run
on:
  schedule:
    - cron:  '0 6 * * *' # tous les jours à 6h
  workflow_dispatch: # permet le déclenchement manuel depuis github.com
jobs:
  download-data-and-analyze-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Setup timezone to Europe/Paris
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Europe/Paris
      - name: Check out to repo
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies from Pipfile
        run: |
          python -m pip install --upgrade pipenv
          pipenv install --deploy
      - name: Run the CLI command to download DECP data
        run: |
          pipenv run python . download --decp-only
      - name: Run the CLI command to download INSEE (Sirene) data
        run: |
          pipenv run python . download --sirens-only
      - name: Run the coverage analysis
        run: |
          pipenv run python . coverage
      - name: Upload audit results as artifact
        uses: actions/upload-artifact@v2
        with: 
          name: coverage.csv
          path: ./data/coverage.csv
          retention-days: 3
      - name: Upload source data as artifact
        uses: actions/upload-artifact@v2
        with: 
          name: decp_augmente.csv
          path: ./data/decp_augmente.csv
          retention-days: 3